const {test}=require('node:test');const assert=require('node:assert/strict');const {executeAttendance}=require('../functions/attendance');
const leader={id:'670939357686923265',rl:true},alice={id:'1001',rl:false},bob={id:'1002',rl:false};
const seed=()=>({accounts:{1001:{profile:{discordName:'alice',displayName:'Alice'},gsBalance:20}},runs:{r:{attendanceSettings:{enabled:true,open:true},settlement:{settlementMode:'coin'},attendance:{},auctions:{}}},attendanceSecrets:{r:{code:'ABC123'}}});
function act(s,a,op,data={},now=100000){return executeAttendance(s,a,op,{runId:'r',...data},now,'NEW123');}
test('self check-in uses authenticated identity and server profile, ignores forged fields',()=>{let s=seed();const o=act(s,alice,'attendanceJoin',{code:'ABC123',character:'Alice',discordId:bob.id,approved:false,discordName:'fake'});const a=o.root.runs.r.attendance.discord_1001;assert.equal(a.discordId,'1001');assert.equal(a.discordName,'alice');assert.equal(a.approved,true);assert.equal(a.checkInSource,'code');assert.deepEqual(o.root.accounts,s.accounts);assert.deepEqual(s.runs.r.attendance,{});});
test('invalid and empty codes never approve; throttling persists and expires',()=>{let s=seed();for(let i=0;i<10;i++){const o=act(s,alice,'attendanceJoin',{code:'WRONG',character:'Alice'});assert.match(o.result.error,/does not match/);s=o.root;}let o=act(s,alice,'attendanceJoin',{code:'ABC123',character:'Alice'});assert.match(o.result.error,/Too many/);assert.deepEqual(o.root.runs.r.attendance,{});o=act(o.root,alice,'attendanceJoin',{code:'ABC123',character:'Alice'},160001);assert.equal(o.result.ok,true);});
test('only leader changes settings or migrates codes',()=>{let s=seed();assert.throws(()=>act(s,alice,'attendanceSettings',{open:true}),/leader/);assert.throws(()=>act(s,alice,'migrateAttendanceCodes'),/leader/);s.runs.old={attendanceSettings:{code:'LEGACY',open:false}};let o=act(s,leader,'migrateAttendanceCodes');assert.equal(o.root.attendanceSecrets.old.code,'LEGACY');assert.equal(o.root.runs.old.attendanceSettings.code,undefined);assert.deepEqual(o.root.accounts,s.accounts);});
test('closed, archived, payout-locked and banned checks reject enrollment',()=>{for(const kind of ['closed','archived','locked','banned']){const s=seed();if(kind==='closed')s.runs.r.attendanceSettings.open=false;if(kind==='archived')s.runs.r.archived=true;if(kind==='locked')s.runs.r.settlement.payoutStarted=true;if(kind==='banned')s.bans={discord_1001:true};assert.throws(()=>act(s,alice,'attendanceJoin',{code:'ABC123',character:'Alice'}));}});
test('duplicate characters rejected and bid identity cannot be changed or removed',()=>{let s=act(seed(),alice,'attendanceJoin',{code:'ABC123',character:'Alice'}).root;assert.throws(()=>act(s,bob,'attendanceJoin',{code:'ABC123',character:'alice'}),/already checked/);s.runs.r.auctions.item={bids:{b:{discordId:'1001',retracted:false}}};assert.throws(()=>act(s,alice,'attendanceJoin',{code:'ABC123',character:'Other'}),/locked after bidding/);assert.throws(()=>act(s,alice,'attendanceLeave'),/locked after bidding/);});
test('leader self-check-in works without a raid code while check-in is closed',()=>{const s=seed();s.runs.r.attendanceSettings.open=false;const o=act(s,leader,'attendanceJoin',{character:'Leader'});assert.equal(o.root.runs.r.attendance['discord_'+leader.id].approved,true);});
test('archive lookup requires both code and verified attendance ownership',()=>{const s=seed();s.runs.r.archived=true;s.runs.r.attendance={discord_1001:{discordId:'1001',character:'Alice'}};assert.equal(act(s,alice,'attendanceArchive',{code:'ABC123'}).result.runId,'r');assert.match(act(s,bob,'attendanceArchive',{code:'ABC123'}).result.error,/No archived/);});
