const {test}=require('node:test'),assert=require('node:assert/strict');
const {executeRunBid}=require('../functions/bids'),{execute}=require('../functions/core');
const actor={id:'111111111111111111',rl:false},now=1800000000000;
const config={enabled:true,accountingMode:'manual',houseId:'670939357686923265'};
const data={runId:'run1',auctionId:'item',amount:6};
function seed(){return {settlement:{settlementMode:'mixed',usdPer1000:6,acceptedCurrencies:{gc:false,gold:true,usd:true}},attendance:{one:{discordId:actor.id,character:'Alice',approved:true}},auctions:{item:{status:'open',currentBid:6,minIncrement:1.5,endsAt:now+10000}}};}
test('run bid preserves core bid results, currency terms and timer extension',()=>{const run=seed(),out=executeRunBid(run,actor,data,'bid_once_123',config,null,now),old=execute({runs:{run1:run},gs:{config}},actor,'placeBid',data,'bid_once_123',now);assert.deepEqual(out.root.auctions,old.root.runs.run1.auctions);assert.deepEqual(out.root.bidOperations.bid_once_123,old.root.gs.ops.bid_once_123);assert.equal(out.root.auctions.item.endsAt,now+30000);assert.equal(run.auctions.item.bids,undefined);});
test('retry is idempotent after auction closure and rejects changed payload',()=>{let run=executeRunBid(seed(),actor,data,'bid_once_123',config,null,now).root;run.auctions.item.status='sold';assert.deepEqual(executeRunBid(run,actor,data,'bid_once_123',config,null,now+60000).root,run);assert.throws(()=>executeRunBid(run,actor,{...data,amount:7.5},'bid_once_123',config,null,now),/reused/);});
test('migrates pre-release operation receipts without placing another bid',()=>{const previous=execute({runs:{run1:seed()},gs:{config}},actor,'placeBid',data,'bid_once_123',now);const out=executeRunBid(previous.root.runs.run1,actor,data,'bid_once_123',config,previous.root.gs.ops.bid_once_123,now);assert.equal(Object.keys(out.root.auctions.item.bids).length,1);assert.ok(out.root.bidOperations.bid_once_123);});
test('minimum, check-in, archive, timer, pause and service checks remain',()=>{for(const change of [r=>r.archived=true,r=>r.attendance={},r=>r.auctions.item.paused=true,r=>r.auctions.item.endsAt=now-1,r=>r.auctions.item.currentBid=20]){const run=seed();change(run);assert.throws(()=>executeRunBid(run,actor,data,'bid_once_123',config,null,now));}assert.throws(()=>executeRunBid(seed(),actor,data,'bid_once_123',{...config,enabled:false},null,now),/not enabled/);});
test('counterbid requires the full increment and stores both accepted bids',()=>{const first=executeRunBid(seed(),actor,data,'bid_once_123',config,null,now).root;assert.throws(()=>executeRunBid(first,actor,{...data,amount:7},'bid_once_456',config,null,now),/minimum/);const second=executeRunBid(first,actor,{...data,amount:7.5},'bid_once_456',config,null,now).root;assert.equal(Object.keys(second.auctions.item.bids).length,2);});
