const {test}=require('node:test');const assert=require('node:assert/strict');
const {execute,balance,units}=require('../functions/core');
let seq=0;const house={id:'1',rl:true},alice={id:'2',rl:false},bob={id:'3',rl:false};
function fixture(){return {runs:{r:{settlement:{},attendance:{a:{character:'Alice',discordId:'2'},b:{character:'Bob',discordId:'3'}}}}};}
function act(s,a,op,data={},id){return execute(s,a,op,data,id||'request_'+(++seq),1700000000000).root;}
function start(){let s=act(fixture(),house,'configure',{address:'0x'+'1'.repeat(40)});s.gs.config.memberGCEnabled=true;return act(s,house,'mode',{runId:'r',mode:'coin',rate:10,lines:{lead:15,treasury:5,risk:5,handling:0}});}
function deposit(s,a,amount){const id='deposit_'+(++seq);s=act(s,a,'depositRequest',{runId:'r',amount},id);return act(s,house,'receive',{id,event:{verified:true,id:'event_'+seq,chainId:1,to:s.gs.config.address,amount:s.gs.deposits[id].amount}});}
function invariant(s){const total=Object.values(s.accounts||{}).reduce((n,a)=>n+balance(a),0)+Object.values(s.gs.withdrawals||{}).filter(w=>w.status==='pending').reduce((n,w)=>n+units(w.amount),0);assert.equal(total,units(s.accounts['1'].usdReserved||0));for(const a of Object.values(s.accounts||{})){assert.equal(balance(a),units(a.gsBalance));assert.equal(balance(a),Object.values(a.tickets||{}).reduce((n,t)=>n+units(t.remainingUsd),0));}}
test('deposit, won item, cuts, withdrawal: reserve and tickets reconcile',()=>{let s=deposit(start(),alice,100);s.runs.r.auctions={item:{status:'sold',currentBid:40,bids:{b:{amount:40,discordId:'2',bidder:'Alice',ts:1}}}};s.runs.r.settlement.raiders={a:{name:'Alice',base:true},b:{name:'Bob',base:true}};s=act(s,alice,'payWin',{runId:'r',auctionId:'item'});assert.equal(s.accounts['2'].gsBalance,60);s=act(s,house,'lockCuts',{runId:'r'});assert.equal(s.accounts['1'].gsBalance,10);s=act(s,house,'creditCut',{runId:'r',raiderKey:'b'});assert.equal(s.accounts['3'].gsBalance,15);s=act(s,bob,'withdraw',{amount:15,address:'0x'+'2'.repeat(40)},'withdraw_001');invariant(s);s=act(s,house,'withdrawPaid',{id:'withdraw_001',event:{verified:true,id:'payout_001',from:s.gs.config.address,to:'0x'+'2'.repeat(40),amount:15}});invariant(s);assert.equal(s.accounts['1'].usdReserved,85);});
test('partial float preserves stamps and mints only remainder',()=>{let s=deposit(start(),house,30);s.runs.r.settlement.usdPer1000=5;s=deposit(s,alice,50);assert.equal(s.accounts['1'].gsBalance,0);assert.equal(s.accounts['1'].usdReserved,50);const t=Object.values(s.accounts['2'].tickets);assert.deepEqual(t.map(t=>[t.remainingUsd,t.rateUsdPer1000]),[[30,10],[20,5]]);invariant(s);});
test('replay cannot mint twice; mismatched operation ID cannot be reused',()=>{let s=start();s=act(s,alice,'depositRequest',{runId:'r',amount:10},'deposit_replay');const d={id:'deposit_replay',event:{verified:true,id:'ev',chainId:1,to:s.gs.config.address,amount:10}};s=act(s,house,'receive',d,'receive_replay');const replay=act(s,house,'receive',d,'receive_replay');assert.deepEqual(replay,s);assert.throws(()=>act(s,house,'receive',d,'another_receive'),/handled/);assert.throws(()=>act(s,house,'receive',{...d,id:'other'},'receive_replay'),/reused/);invariant(s);});
test('insufficient funds, bans and false receipts leave original state unchanged',()=>{const s=start(),before=JSON.stringify(s);assert.throws(()=>act(s,alice,'withdraw',{amount:1,address:'0x'+'2'.repeat(40)}),/Insufficient/);assert.equal(JSON.stringify(s),before);s.bans={discord_2:{}};assert.throws(()=>deposit(s,alice,10),/banned/);assert.throws(()=>act(s,alice,'configure',{address:'0x'+'1'.repeat(40)}),/banned/);});
test('FIFO refunds preserve rate, no double payment, retracted winner cannot be charged',()=>{let s=deposit(start(),alice,100);s.runs.r.auctions={i:{status:'sold',currentBid:20,bids:{b:{amount:20,discordId:'2',ts:1}}}};s=act(s,alice,'payWin',{runId:'r',auctionId:'i'});assert.throws(()=>act(s,alice,'payWin',{runId:'r',auctionId:'i'}),/already paid/);s=act(s,house,'refundWin',{runId:'r',auctionId:'i'});assert.equal(s.accounts['2'].gsBalance,100);s.runs.r.auctions.i.bids.b.retracted=true;assert.throws(()=>act(s,house,'payWin',{runId:'r',auctionId:'i'}),/Winner/);invariant(s);});
test('withdraw reservation prevents double spend and cancellation restores tickets',()=>{let s=deposit(start(),alice,20);s=act(s,alice,'withdraw',{amount:15,address:'0x'+'2'.repeat(40)},'withdraw_test');assert.throws(()=>act(s,alice,'withdraw',{amount:10,address:'0x'+'2'.repeat(40)}),/Insufficient/);s=act(s,alice,'withdrawCancel',{id:'withdraw_test'});assert.equal(s.accounts['2'].gsBalance,20);invariant(s);});
test('archive credit targets only selected run; funded bonus does not change other cut',()=>{let s=deposit(start(),alice,100);s=deposit(s,house,20);s.runs.r.auctions={i:{status:'sold',currentBid:40,bids:{b:{amount:40,discordId:'2',ts:1}}}};s.runs.r.settlement.raiders={a:{name:'Alice'},b:{name:'Bob'}};s=act(s,alice,'payWin',{runId:'r',auctionId:'i'});s=act(s,house,'lockCuts',{runId:'r'});s.runs.r.archived=true;s.runs.current={settlement:{},auctions:{}};const current=JSON.stringify(s.runs.current),other=s.runs.r.settlement.raiders.b.gsCut;s=act(s,house,'adjustCut',{runId:'r',raiderKey:'a',amount:5,reason:'Bonus'});assert.equal(s.runs.r.settlement.raiders.b.gsCut,other);s=act(s,house,'creditCut',{runId:'r',raiderKey:'a'});assert.equal(JSON.stringify(s.runs.current),current);invariant(s);});
test('assigned receipt and explicit mint override remain fully backed',()=>{let s=deposit(start(),house,10);s=act(s,house,'assignDeposit',{owner:'2',runId:'r',forceMint:true,event:{verified:true,id:'unmatched_1',chainId:1,to:s.gs.config.address,amount:5,blockTime:1}});assert.equal(s.accounts['1'].gsBalance,10);assert.equal(s.accounts['2'].gsBalance,5);assert.equal(s.accounts['1'].usdReserved,15);invariant(s);});
test('gold payout uses the selected rate and legacy runs retain ticket rates',()=>{let s=deposit(start(),house,100);s.runs.r.settlement.settlementMode='mixed';s.runs.r.settlement.goldEnabled=true;s.runs.r.settlement.usdPer1000=5;s.runs.r.settlement.raiders={a:{name:'Alice'}};s.runs.r.auctions={i:{status:'sold',currentBid:40,bids:{b:{amount:40,discordId:'2',ts:1}}}};s=act(s,house,'payWin',{runId:'r',auctionId:'i',gold:true});s=act(s,house,'lockCuts',{runId:'r'});s=act(s,alice,'payoutChoice',{runId:'r',raiderKey:'a',method:'gold'});const legacy=JSON.parse(JSON.stringify(s));delete legacy.runs.r.settlement.payoutUsdPer1000;assert.throws(()=>act(legacy,house,'creditCut',{runId:'r',raiderKey:'a',goldDelivered:true,expectedGold:6000}),/quote changed/);invariant(act(legacy,house,'creditCut',{runId:'r',raiderKey:'a',goldDelivered:true,expectedGold:3000}));assert.equal(s.runs.r.settlement.payoutUsdPer1000,5);assert.throws(()=>act(s,house,'creditCut',{runId:'r',raiderKey:'a',goldDelivered:true,expectedGold:3000}),/quote changed/);s=act(s,house,'creditCut',{runId:'r',raiderKey:'a',goldDelivered:true,expectedGold:6000});assert.equal(s.runs.r.settlement.raiders.a.gsCredited,30);invariant(s);});
test('haircuts apply once, at the published percentage, to unused lots only',()=>{let s=deposit(start(),alice,100);s.runs.r.settlement.gsHaircutPct=5;for(const t of Object.values(s.accounts['2'].tickets))t.expiresAt=10;s=act(s,house,'haircut',{owner:'2'});assert.equal(s.accounts['2'].gsBalance,95);assert.throws(()=>act(s,house,'haircut',{owner:'2'}),/eligible/);invariant(s);});
test('server bidding binds Discord identity and requires live auction and minimum',()=>{let s=start();s.runs.r.attendance.a.approved=true;s.runs.r.auctions={i:{status:'open',currentBid:10,minIncrement:1,endsAt:1700000100000}};s=act(s,alice,'placeBid',{runId:'r',auctionId:'i',amount:10});assert.equal(Object.values(s.runs.r.auctions.i.bids)[0].discordId,'2');assert.throws(()=>act(s,alice,'placeBid',{runId:'r',auctionId:'i',amount:10}),/minimum/);s.runs.r.archived=true;assert.throws(()=>act(s,alice,'placeBid',{runId:'r',auctionId:'i',amount:11}),/not live/);});
