const {test}=require('node:test'),assert=require('node:assert/strict');
const {execute,balance,units}=require('../functions/core');
const leader={id:'1',rl:true},alice={id:'2',rl:false};let seq=0;const now=1700000000000;
const act=(s,a,op,data={},id)=>execute(s,a,op,data,id||'currency_'+(++seq),now).root;
function seed(c){const acct=(n)=>({gsBalance:n,ledger:{seed:{unit:'GS',gsDelta:n}},tickets:{seed:{id:'seed',createdAt:1,remainingUsd:n,usd:n,rateUsdPer1000:10,runId:'r'}}});return {gs:{config:{enabled:true,houseId:'1',address:'0x'+'1'.repeat(40)}},accounts:{'1':{...acct(100),usdReserved:200},'2':acct(100)},runs:{r:{settlement:{settlementMode:'mixed',goldEnabled:true,usdPer1000:10,acceptedCurrencies:c},attendance:{a:{character:'Alice',discordId:'2',approved:true}},auctions:{i:{status:'open',currentBid:10,minIncrement:1,endsAt:now+60000}}}}};}
function invariant(s){let total=0;for(const a of Object.values(s.accounts)){assert.equal(balance(a),units(a.gsBalance));assert.equal(balance(a),Object.values(a.tickets||{}).reduce((n,t)=>n+units(t.remainingUsd),0));total+=balance(a);}assert.equal(total,units(s.accounts['1'].usdReserved));}
for(let bits=1;bits<8;bits++)test('currency combination '+bits+' enforces each payment method',()=>{const c={gc:!!(bits&1),gold:!!(bits&2),usd:!!(bits&4)};let s=act(seed(c),alice,'placeBid',{runId:'r',auctionId:'i',amount:10});s.runs.r.auctions.i.status='sold';for(const [method,k,actor] of [['gs','gc',alice],['gold','gold',leader],['usd','usd',leader]]){const data={runId:'r',auctionId:'i',method,externalReceived:true};if(c[k]){const paid=act(s,actor,'payWin',data);assert.equal(paid.runs.r.settlement.gsPayments.i.method,method);invariant(paid);}else assert.throws(()=>act(s,actor,'payWin',data),/not accepted/);}});
test('empty selection, nonleaders, archived and locked changes rejected without mutation',()=>{const s=seed({gc:true,gold:false,usd:false}),before=structuredClone(s);assert.throws(()=>act(s,leader,'currencies',{runId:'r',currencies:{gc:false,gold:false,usd:false}}),/at least one/);assert.throws(()=>act(s,alice,'currencies',{runId:'r',currencies:{gc:false,gold:true,usd:false}}),/leader/);assert.deepEqual(s,before);s.runs.r.archived=true;assert.throws(()=>act(s,leader,'currencies',{runId:'r',currencies:{gc:true,gold:true,usd:true}}),/closed/);s.runs.r.archived=false;s.runs.r.settlement.payoutStarted=true;assert.throws(()=>act(s,leader,'currencies',{runId:'r',currencies:{gc:true,gold:true,usd:true}}),/closed/);});
test('mid-run changes preserve old bids, payment records and rate while applying to new bids',()=>{let s=seed({gc:true,gold:true,usd:false});s=act(s,alice,'placeBid',{runId:'r',auctionId:'i',amount:10});s.runs.r.auctions.legacy={status:'sold',currentBid:5,bids:{legacy:{amount:5,discordId:'2',ts:1}}};s.runs.r.settlement.gsPayments={other:{status:'paid',method:'gold',amount:1,rateUsdPer1000:7}};const receipt=structuredClone(s.runs.r.settlement.gsPayments.other);s=act(s,leader,'currencies',{runId:'r',currencies:{gc:false,gold:false,usd:true}});assert.equal(s.runs.r.settlement.usdPer1000,10);assert.deepEqual(s.runs.r.settlement.gsPayments.other,receipt);assert.deepEqual(s.runs.r.auctions.legacy.bids.legacy.acceptedCurrencies,{gc:true,gold:true,usd:false});assert.deepEqual(Object.values(s.runs.r.auctions.i.bids)[0].acceptedCurrencies,{gc:true,gold:true,usd:false});s=act(s,alice,'placeBid',{runId:'r',auctionId:'i',amount:11});assert.deepEqual(Object.values(s.runs.r.auctions.i.bids)[1].acceptedCurrencies,{gc:false,gold:false,usd:true});});
test('USD receipts need leader confirmation, cannot duplicate, refund requires external return',()=>{let s=seed({gc:false,gold:false,usd:true});s=act(s,alice,'placeBid',{runId:'r',auctionId:'i',amount:10});s.runs.r.auctions.i.status='sold';const d={runId:'r',auctionId:'i',method:'usd',externalReceived:true,expectedAmount:10};assert.throws(()=>act(s,alice,'payWin',d),/leader/);assert.throws(()=>act(s,leader,'payWin',{...d,externalReceived:false}),/Confirm/);assert.throws(()=>act(s,leader,'payWin',{...d,expectedAmount:11}),/Price changed/);s=act(s,leader,'payWin',d,'receipt_once');assert.equal(s.accounts['2'].gsBalance,100);assert.equal(s.accounts['1'].gsBalance,90);assert.deepEqual(act(s,leader,'payWin',d,'receipt_once'),s);assert.throws(()=>act(s,leader,'payWin',d),/already paid/);assert.throws(()=>act(s,leader,'refundWin',{runId:'r',auctionId:'i'}),/Confirm USD/);s=act(s,leader,'refundWin',{runId:'r',auctionId:'i',externalReturned:true});assert.equal(s.accounts['1'].gsBalance,100);assert.equal(s.accounts['2'].gsBalance,100);invariant(s);});
test('gold receipt honors winning bid rate; unfunded treasury cannot record receipt',()=>{let s=seed({gc:false,gold:true,usd:false});s=act(s,alice,'placeBid',{runId:'r',auctionId:'i',amount:10});s.runs.r.auctions.i.status='sold';s.runs.r.settlement.usdPer1000=20;const paid=act(s,leader,'payWin',{runId:'r',auctionId:'i',method:'gold'});assert.equal(paid.runs.r.settlement.gsPayments.i.goldAmount,1000);s.accounts['1'].ledger={};s.accounts['1'].tickets={};s.accounts['1'].gsBalance=0;assert.throws(()=>act(s,leader,'payWin',{runId:'r',auctionId:'i',method:'gold'}),/Insufficient/);});
