const {test}=require('node:test'),assert=require('node:assert/strict');const {execute,balance,units}=require('../functions/core');
const leader={id:'670939357686923265',rl:true},alice={id:'111111111111111111',rl:false};let count=0;const now=1800000000000;
function act(s,a,op,data={},id){return execute(s,a,op,data,id||'manual_'+(++count),now).root;}
function seed(){return act({runs:{r:{settlement:{settlementMode:'coin',usdPer1000:10,acceptedCurrencies:{gc:true,gold:true,usd:true},gsCutLines:{lead:25,treasury:0,risk:0,handling:0}},attendance:{a:{discordId:alice.id,character:'Alice',approved:true}},auctions:{item:{status:'open',currentBid:10,minIncrement:1,endsAt:now+60000}}}}},leader,'manualInitialize');}
const data={owner:alice.id,amount:20,reference:'receipt-123',reason:'USDC received manually',received:true,runId:'r'};
function invariant(s){let sum=0;for(const a of Object.values(s.accounts||{})){assert.equal(balance(a),units(a.gsBalance));assert.equal(balance(a),Object.values(a.tickets||{}).reduce((n,t)=>n+units(t.remainingUsd),0));sum+=balance(a);}sum+=Object.values(s.gs.withdrawals||{}).filter(w=>w.status==='pending').reduce((n,w)=>n+units(w.amount),0);assert.equal(sum,units(s.accounts?.[leader.id]?.usdReserved||0));}
test('only leader can initialize or credit; confirmation and reason required',()=>{assert.throws(()=>act({},alice,'manualInitialize'),/leader/);const s=seed();assert.throws(()=>act(s,alice,'manualCredit',data),/leader/);assert.throws(()=>act(s,leader,'manualCredit',{...data,received:false}),/Confirm/);assert.throws(()=>act(s,leader,'manualCredit',{...data,reason:''}),/reason/);assert.throws(()=>act(s,leader,'manualCredit',{...data,amount:-1}),/positive/);});
test('manual credit is audited and deduplicated across retries and reference reuse',()=>{let s=act(seed(),leader,'manualCredit',data,'manual_credit_once');invariant(s);assert.equal(s.accounts[alice.id].gsBalance,20);assert.equal(s.gs.manualReceipts.manual_credit_once.confirmedBy,leader.id);assert.deepEqual(act(s,leader,'manualCredit',data,'manual_credit_once'),s);assert.throws(()=>act(s,leader,'manualCredit',data),/already recorded/);assert.throws(()=>act(s,leader,'manualCredit',{...data,reference:' RECEIPT-123 '}),/already recorded/);});
test('manual payout reserves funds, can cancel, and can only be completed once by leader',()=>{let s=act(seed(),leader,'manualCredit',data);s=act(s,alice,'manualWithdraw',{amount:5,details:'Arrange via Discord'},'manual_withdraw_a');invariant(s);assert.equal(s.accounts[alice.id].gsBalance,15);assert.throws(()=>act(s,alice,'manualWithdrawPaid',{id:'manual_withdraw_a',paid:true,reference:'payout1'}),/leader/);s=act(s,alice,'withdrawCancel',{id:'manual_withdraw_a'});invariant(s);assert.equal(s.accounts[alice.id].gsBalance,20);s=act(s,alice,'manualWithdraw',{amount:5,details:'Discord payout'},'manual_withdraw_b');s=act(s,leader,'manualWithdrawPaid',{id:'manual_withdraw_b',paid:true,reference:'payout1'});invariant(s);assert.throws(()=>act(s,leader,'manualWithdrawPaid',{id:'manual_withdraw_b',paid:true,reference:'payout2'}),/unavailable/);});
test('GC auction payment and refund preserve manual ledger',()=>{let s=act(seed(),leader,'manualCredit',data);s=act(s,alice,'placeBid',{runId:'r',auctionId:'item',amount:10});s.runs.r.auctions.item.status='sold';s=act(s,alice,'payWin',{runId:'r',auctionId:'item',method:'gs'});invariant(s);assert.equal(s.accounts[alice.id].gsBalance,10);s=act(s,leader,'refundWin',{runId:'r',auctionId:'item'});invariant(s);assert.equal(s.accounts[alice.id].gsBalance,20);});
for(const method of ['gold','usd'])test('manual '+method+' collection and external refund require confirmation and no prefunded house',()=>{let s=seed();s=act(s,alice,'placeBid',{runId:'r',auctionId:'item',amount:10});s.runs.r.auctions.item.status='sold';assert.throws(()=>act(s,leader,'payWin',{runId:'r',auctionId:'item',method}),/Confirm/);s=act(s,leader,'payWin',{runId:'r',auctionId:'item',method,externalReceived:true});invariant(s);assert.equal(s.accounts._run_r.gsBalance,10);s=act(s,leader,'refundWin',{runId:'r',auctionId:'item',goldReturned:true,externalReturned:true});invariant(s);assert.equal(s.accounts._run_r.gsBalance,0);});
test('manual receipt distributes cut and admin cut with conserved balances',()=>{let s=act(seed(),leader,'manualCredit',data);s=act(s,alice,'placeBid',{runId:'r',auctionId:'item',amount:10});s.runs.r.auctions.item.status='sold';s.runs.r.settlement.raiders={a:{name:'Alice',base:true}};s=act(s,alice,'payWin',{runId:'r',auctionId:'item',method:'gs'});s=act(s,leader,'lockCuts',{runId:'r'});s=act(s,leader,'creditCut',{runId:'r',raiderKey:'a'});invariant(s);assert.equal(s.accounts[alice.id].gsBalance,17.5);assert.equal(s.accounts[leader.id].gsBalance,2.5);});
