const fs=require('node:fs');
const rl="auth != null && auth.token.raidLeader === true && !root.child('bans').child('discord_' + auth.token.discordId).exists()";
const member="auth != null && auth.token.discordId != null && !root.child('bans').child('discord_' + auth.token.discordId).exists()";
const legacy="!root.child('runs').child($run).child('settlement/settlementMode').exists()";
const self="auth != null && auth.uid === 'discord_' + $id && !root.child('bans').child('discord_' + $id).exists()";
const row="root.child('runs').child($run).child('settlement/raiders').child($raider)";
// Coin ownership is stamped by the backend when cuts lock. Never fall back to names.
const own=`(${member}) && auth.uid === 'discord_' + auth.token.discordId && ((${legacy}) ? (${row}.child('name').isString() && root.child('runs').child($run).child('attendance').child('discord_' + auth.token.discordId).child('character').val() === ${row}.child('name').val()) : (${row}.child('gsOwner').isString() && ${row}.child('gsOwner').val() === auth.token.discordId))`;
const rw=w=>({'.write':w});const rules={'.read':false,'.write':false,gs:{'.read':false,'.write':false}};
rules.accounts={'.read':rl,'$id':{'.read':`(${self}) || (${rl})`,profile:rw(`(${self}) || (${rl})`),tickets:rw(false),gsBalance:rw(false),usdReserved:rw(false),ledger:{'$entry':rw(`(${rl}) && (!data.exists() || data.child('unit').val() !== 'GS') && (!newData.exists() || newData.child('unit').val() !== 'GS')`)},creditRequests:{'$request':rw(`(${rl}) || ((${self}) && ((!data.exists() && newData.child('status').val() === 'pending') || (data.child('status').val() === 'pending' && newData.child('status').val() === 'cancelled')))` )},withdrawals:{'$request':rw(`(${rl}) || ((${self}) && newData.child('status').val() === 'submitted')`)}}};
const run=rw(`(${rl}) && (${legacy} || (!data.exists() && !newData.child('settlement/gsPayments').exists() && (newData.child('settlement/payoutStarted').val() !== true)))`);
for(const key of ['settings','archived','archivedAt','attendanceSettings','siteContent','lootDisplay','archiveDisplay','cardOrder','cardDrag','cardDragPreview'])run[key]=rw(rl);
for(const key of ['presence','nicks','chat','audit'])run[key]=rw(member);
run.attendance={'$id':rw(`(${rl}) || ((${member}) && $id === 'discord_' + auth.token.discordId && (!newData.exists() || newData.child('discordId').val() === auth.token.discordId))`)};
run.auctions={'$auction':{'.write':`(${rl}) && root.child('runs').child($run).child('settlement/gsPayments').child($auction).child('status').val() !== 'paid'`,bids:{'$bid':rw(`(${legacy}) && (${member}) && ((!data.exists() && newData.child('discordId').val() === auth.token.discordId) || data.child('discordId').val() === auth.token.discordId)`)},currentBid:rw(`(${legacy}) && (${member})`),order:rw(rl)}};
const raider=rw(`(${rl}) && (root.child('runs').child($run).child('settlement/payoutStarted').val() !== true)`);
raider.cutRequest=rw(`(${rl}) || (${own})`);raider.cutDisputeHistory={'$event':rw(`!data.exists() && ((${rl}) || (${own}))`)};raider.submission=rw(`(${legacy}) && ((${rl}) || (${own}))`);
for(const k of ['base','adjustGold','adjustPct','mutators'])raider[k]=rw(`(${rl}) && root.child('runs').child($run).child('settlement/setupUnlocked').val() === true`);
run.settlement={raiders:{'$raider':raider},mutators:rw(`(${rl}) && ((root.child('runs').child($run).child('settlement/payoutStarted').val() !== true) || root.child('runs').child($run).child('settlement/setupUnlocked').val() === true)`),setupUnlocked:rw(rl),performanceImports:rw(rl),performanceDraft:rw(rl)};
rules.runs={'.read':member,'$run':run};rules.bans={'.read':true,'.write':rl};rules.audit={'.read':rl,'$run':{'$event':rw(`${member} && !data.exists()`)}};
rules.discordProfiles={'$id':{'.read':`(${self}) || (${rl})`,'.write':`(${self}) || (${rl})`}};
rules.siteFeedback={'.read':rl,'$id':rw(`(${rl}) || ((${member}) && !data.exists() && newData.child('discordId').val() === auth.token.discordId)`)};
rules.siteFeedbackAttachments={'$id':{'.read':rl,'.write':`${member} && !data.exists()`}};
rules.cutDisputeAttachments={'$run':{'$raider':{'.read':`(${rl}) || (${own})`,'.write':`(${rl}) || (${own})`}}};
fs.writeFileSync(__dirname+'/database.rules.json',JSON.stringify({rules},null,2));
